//colors
export const GENERATE_COLOR_REQUEST = 'GENERATE_COLOR_REQUEST';
export const GENERATE_COLOR_SUCCESS = 'GENERATE_COLOR_SUCCESS';
export const CHANGE_COLOR = 'CHANGE_COLOR';
export const COPY_COLOR_TO_CLIPBOARD = 'COPY_COLOR_TO_CLIPBOARD';

//gradients
export const GENERATE_GRADIENT_REQUEST = 'GENERATE_GRADIENT_REQUEST';
export const GENERATE_GRADIENT_SUCCESS = 'GENERATE_GRADIENT_SUCCESS';
export const CHANGE_GRADIENT = 'CHANGE_GRADIENT';
export const COPY_GRADIENT_TO_CLIPBOARD = 'COPY_GRADIENT_TO_CLIPBOARD';
export const ADD_NEW_COLOR = 'ADD_NEW_COLOR';
export const EDIT_ANGLE = 'EDIT_ANGLE';
export const CHANGE_GRADIENT_DIRECTION = 'CHANGE_GRADIENT_DIRECTION';
export const TOGGLE_EDIT_COLOR_OF_GRADIENT = 'TOGGLE_EDIT_COLOR_OF_GRADIENT';
export const EDIT_COLOR_OF_GRADIENT = 'EDIT_COLOR_OF_GRADIENT';
export const TOGGLE_SLIDER = 'TOGGLE_SLIDER';
export const START_UPDATE_COLOR_STOP = 'START_UPDATE_COLOR_STOP';
export const UPDATE_COLOR_STOP = 'UPDATE_COLOR_STOP';

//settings
export const TOGGLE_PREFIX = 'TOGGLE_PREFIXES';
export const TOGGLE_FALLBACK = 'TOGGLE_FALLBACK';
