//colors
export const GENERATE_COLOR_REQUEST = 'GENERATE_COLOR_REQUEST';
export const GENERATE_COLOR_SUCCESS = 'GENERATE_COLOR_SUCCESS';
export const CHANGE_COLOR = 'CHANGE_COLOR';
export const COPY_COLOR_TO_CLIPBOARD = 'COPY_COLOR_TO_CLIPBOARD';

//gradients
export const GENERATE_GRADIENT_REQUEST = 'GENERATE_GRADIENT_REQUEST';
export const GENERATE_GRADIENT_SUCCESS = 'GENERATE_GRADIENT_SUCCESS';
export const CHANGE_GRADIENT = 'CHANGE_GRADIENT';
export const COPY_GRADIENT_TO_CLIPBOARD = 'COPY_GRADIENT_TO_CLIPBOARD';
export const ADD_NEW_COLOR = 'ADD_NEW_COLOR';
export const EDIT_ANGLE = 'EDIT_ANGLE';
