export const GENERATE_COLOR_REQUEST = 'GENERATE_COLOR_REQUEST';
export const GENERATE_COLOR_SUCCESS = 'GENERATE_COLOR_SUCCESS';
export const CHANGE_COLOR = 'CHANGE_COLOR';
export const COPY_COLOR_TO_CLIPBOARD = 'COPY_COLOR_TO_CLIPBOARD';
